spring:
  datasource:
    url: jdbc:mysql://localhost:3306/burcuatici_api
    username: burcuatici
    password: burcuatici123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

sms:
  api:
    url: https://api.vatansms.net/api/v1/1toN
    id: c4fdfaee2461a91318f137e2
    key: 4edc2818d83ed6d208a53bf8
